CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(150) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(30),
    password VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'RESPONDER', 'VIEWER'))
);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description TEXT NOT NULL,
    severity VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    title VARCHAR(150) NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    assigned_user_id BIGINT,
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT incidents_pkey PRIMARY KEY (id),
    CONSTRAINT incidents_severity_check CHECK (severity IN ('SEV1', 'SEV2', 'SEV3', 'SEV4')),
    CONSTRAINT incidents_status_check CHECK (
        status IN ('OPEN', 'INVESTIGATING', 'IDENTIFIED', 'MONITORING', 'RESOLVED')
    ),
    CONSTRAINT fkbhno9fbt616ap32tmavdn80gn
        FOREIGN KEY (assigned_user_id) REFERENCES users (id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    author_id BIGINT NOT NULL,
    incident_id BIGINT NOT NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT fkn2na60ukhs76ibtpt9burkm27
        FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fkrm5f8poow5xsnj1qdnntjqcxh
        FOREIGN KEY (incident_id) REFERENCES incidents (id)
);

CREATE TABLE incident_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    action VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    new_value TEXT,
    old_value TEXT,
    incident_id BIGINT NOT NULL,
    performed_by_user_id BIGINT,
    CONSTRAINT incident_history_pkey PRIMARY KEY (id),
    CONSTRAINT incident_history_action_check CHECK (
        action IN ('CREATED', 'STATUS_CHANGED', 'SEVERITY_CHANGED', 'ASSIGNED', 'COMMENT_ADDED')
    ),
    CONSTRAINT fkd2x9fkmp36ty1sptf7y0lyhb1
        FOREIGN KEY (incident_id) REFERENCES incidents (id),
    CONSTRAINT fkgaiyx5ueeyj8b5rjkvybjtoss
        FOREIGN KEY (performed_by_user_id) REFERENCES users (id)
);
